defaults:
    - agent: sac 

env: ant-expert-v2
algorithm: SAC

# this needs to be specified manually
experiment: state 

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 1000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true
save_model: false 
save_actor: true


seed: 1


# hydra configuration
work_dir: "."
env_dir: ${work_dir}/${env}_${experiment}_${algorithm}
hydra: 
    run:
        dir: ${work_dir}/${env_dir}
    sweep:    
        dir: ${env_dir} 
        subdir: seed${seed}
    job:
        config:   
            override_dirname:        
                kv_sep: '='        
                item_sep: ','        
                exclude_keys: []
