defaults:
    - agent: sac

env: cheetah_run

# this needs to be specified manually
experiment: test_exp

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 1000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true
save_model: false 
save_actor: true


seed: 1


# hydra configuration
work_dir: "."
hydra:
    run:
        dir: ${work_dir}/${env}_${experiment}_${now:%H%M}
